import "./globals.css";
import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import Navbar from "./components/navbar";

const font = PT_Serif({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
